// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfvBOcUXT1M51ik2_vbGKmoCF65de0Fy4',
    appId: '1:112580489904:web:2a7e8492af38f428d8c175',
    messagingSenderId: '112580489904',
    projectId: 'castle-watch-29837',
    authDomain: 'castle-watch-29837.firebaseapp.com',
    storageBucket: 'castle-watch-29837.firebasestorage.app',
    measurementId: 'G-C2ZVWJ5E06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkXTlg-waXG7vj2pKJtF5TLBXz4XRGlaE',
    appId: '1:112580489904:android:cd5f473ca73186add8c175',
    messagingSenderId: '112580489904',
    projectId: 'castle-watch-29837',
    storageBucket: 'castle-watch-29837.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXHHSTh9TSNTOwKbbhT57bSl2OFNcaUhA',
    appId: '1:112580489904:ios:d2c40b6790bc107ad8c175',
    messagingSenderId: '112580489904',
    projectId: 'castle-watch-29837',
    storageBucket: 'castle-watch-29837.firebasestorage.app',
    iosBundleId: 'com.example.castleWatch',
  );
}
